#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnn.WebAnalytics
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dnn9")]
	public partial class DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPortal(Portal instance);
    partial void UpdatePortal(Portal instance);
    partial void DeletePortal(Portal instance);
    partial void InsertTab(Tab instance);
    partial void UpdateTab(Tab instance);
    partial void DeleteTab(Tab instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertCommunity_Visit(Community_Visit instance);
    partial void UpdateCommunity_Visit(Community_Visit instance);
    partial void DeleteCommunity_Visit(Community_Visit instance);
    partial void InsertCommunity_Visitor(Community_Visitor instance);
    partial void UpdateCommunity_Visitor(Community_Visitor instance);
    partial void DeleteCommunity_Visitor(Community_Visitor instance);
    #endregion
		
		public DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Portal> Portals
		{
			get
			{
				return this.GetTable<Portal>();
			}
		}
		
		public System.Data.Linq.Table<Tab> Tabs
		{
			get
			{
				return this.GetTable<Tab>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Community_Visit> Community_Visits
		{
			get
			{
				return this.GetTable<Community_Visit>();
			}
		}
		
		public System.Data.Linq.Table<Community_Visitor> Community_Visitors
		{
			get
			{
				return this.GetTable<Community_Visitor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Portals")]
	public partial class Portal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PortalID;
		
		private System.Nullable<System.DateTime> _ExpiryDate;
		
		private int _UserRegistration;
		
		private int _BannerAdvertising;
		
		private System.Nullable<int> _AdministratorId;
		
		private string _Currency;
		
		private decimal _HostFee;
		
		private int _HostSpace;
		
		private System.Nullable<int> _AdministratorRoleId;
		
		private System.Nullable<int> _RegisteredRoleId;
		
		private System.Guid _GUID;
		
		private string _PaymentProcessor;
		
		private string _ProcessorUserId;
		
		private string _ProcessorPassword;
		
		private System.Nullable<int> _SiteLogHistory;
		
		private string _DefaultLanguage;
		
		private int _TimezoneOffset;
		
		private string _HomeDirectory;
		
		private int _PageQuota;
		
		private int _UserQuota;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private System.Nullable<int> _PortalGroupID;
		
		private EntitySet<Tab> _Tabs;
		
		private EntitySet<Community_Visitor> _Community_Visitors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnExpiryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiryDateChanged();
    partial void OnUserRegistrationChanging(int value);
    partial void OnUserRegistrationChanged();
    partial void OnBannerAdvertisingChanging(int value);
    partial void OnBannerAdvertisingChanged();
    partial void OnAdministratorIdChanging(System.Nullable<int> value);
    partial void OnAdministratorIdChanged();
    partial void OnCurrencyChanging(string value);
    partial void OnCurrencyChanged();
    partial void OnHostFeeChanging(decimal value);
    partial void OnHostFeeChanged();
    partial void OnHostSpaceChanging(int value);
    partial void OnHostSpaceChanged();
    partial void OnAdministratorRoleIdChanging(System.Nullable<int> value);
    partial void OnAdministratorRoleIdChanged();
    partial void OnRegisteredRoleIdChanging(System.Nullable<int> value);
    partial void OnRegisteredRoleIdChanged();
    partial void OnGUIDChanging(System.Guid value);
    partial void OnGUIDChanged();
    partial void OnPaymentProcessorChanging(string value);
    partial void OnPaymentProcessorChanged();
    partial void OnProcessorUserIdChanging(string value);
    partial void OnProcessorUserIdChanged();
    partial void OnProcessorPasswordChanging(string value);
    partial void OnProcessorPasswordChanged();
    partial void OnSiteLogHistoryChanging(System.Nullable<int> value);
    partial void OnSiteLogHistoryChanged();
    partial void OnDefaultLanguageChanging(string value);
    partial void OnDefaultLanguageChanged();
    partial void OnTimezoneOffsetChanging(int value);
    partial void OnTimezoneOffsetChanged();
    partial void OnHomeDirectoryChanging(string value);
    partial void OnHomeDirectoryChanged();
    partial void OnPageQuotaChanging(int value);
    partial void OnPageQuotaChanged();
    partial void OnUserQuotaChanging(int value);
    partial void OnUserQuotaChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    partial void OnPortalGroupIDChanging(System.Nullable<int> value);
    partial void OnPortalGroupIDChanged();
    #endregion
		
		public Portal()
		{
			this._Tabs = new EntitySet<Tab>(new Action<Tab>(this.attach_Tabs), new Action<Tab>(this.detach_Tabs));
			this._Community_Visitors = new EntitySet<Community_Visitor>(new Action<Community_Visitor>(this.attach_Community_Visitors), new Action<Community_Visitor>(this.detach_Community_Visitors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiryDate
		{
			get
			{
				return this._ExpiryDate;
			}
			set
			{
				if ((this._ExpiryDate != value))
				{
					this.OnExpiryDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiryDate = value;
					this.SendPropertyChanged("ExpiryDate");
					this.OnExpiryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRegistration", DbType="Int NOT NULL")]
		public int UserRegistration
		{
			get
			{
				return this._UserRegistration;
			}
			set
			{
				if ((this._UserRegistration != value))
				{
					this.OnUserRegistrationChanging(value);
					this.SendPropertyChanging();
					this._UserRegistration = value;
					this.SendPropertyChanged("UserRegistration");
					this.OnUserRegistrationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BannerAdvertising", DbType="Int NOT NULL")]
		public int BannerAdvertising
		{
			get
			{
				return this._BannerAdvertising;
			}
			set
			{
				if ((this._BannerAdvertising != value))
				{
					this.OnBannerAdvertisingChanging(value);
					this.SendPropertyChanging();
					this._BannerAdvertising = value;
					this.SendPropertyChanged("BannerAdvertising");
					this.OnBannerAdvertisingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdministratorId", DbType="Int")]
		public System.Nullable<int> AdministratorId
		{
			get
			{
				return this._AdministratorId;
			}
			set
			{
				if ((this._AdministratorId != value))
				{
					this.OnAdministratorIdChanging(value);
					this.SendPropertyChanging();
					this._AdministratorId = value;
					this.SendPropertyChanged("AdministratorId");
					this.OnAdministratorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="Char(3)")]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this.OnCurrencyChanging(value);
					this.SendPropertyChanging();
					this._Currency = value;
					this.SendPropertyChanged("Currency");
					this.OnCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostFee", DbType="Money NOT NULL")]
		public decimal HostFee
		{
			get
			{
				return this._HostFee;
			}
			set
			{
				if ((this._HostFee != value))
				{
					this.OnHostFeeChanging(value);
					this.SendPropertyChanging();
					this._HostFee = value;
					this.SendPropertyChanged("HostFee");
					this.OnHostFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostSpace", DbType="Int NOT NULL")]
		public int HostSpace
		{
			get
			{
				return this._HostSpace;
			}
			set
			{
				if ((this._HostSpace != value))
				{
					this.OnHostSpaceChanging(value);
					this.SendPropertyChanging();
					this._HostSpace = value;
					this.SendPropertyChanged("HostSpace");
					this.OnHostSpaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdministratorRoleId", DbType="Int")]
		public System.Nullable<int> AdministratorRoleId
		{
			get
			{
				return this._AdministratorRoleId;
			}
			set
			{
				if ((this._AdministratorRoleId != value))
				{
					this.OnAdministratorRoleIdChanging(value);
					this.SendPropertyChanging();
					this._AdministratorRoleId = value;
					this.SendPropertyChanged("AdministratorRoleId");
					this.OnAdministratorRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteredRoleId", DbType="Int")]
		public System.Nullable<int> RegisteredRoleId
		{
			get
			{
				return this._RegisteredRoleId;
			}
			set
			{
				if ((this._RegisteredRoleId != value))
				{
					this.OnRegisteredRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RegisteredRoleId = value;
					this.SendPropertyChanged("RegisteredRoleId");
					this.OnRegisteredRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentProcessor", DbType="NVarChar(50)")]
		public string PaymentProcessor
		{
			get
			{
				return this._PaymentProcessor;
			}
			set
			{
				if ((this._PaymentProcessor != value))
				{
					this.OnPaymentProcessorChanging(value);
					this.SendPropertyChanging();
					this._PaymentProcessor = value;
					this.SendPropertyChanged("PaymentProcessor");
					this.OnPaymentProcessorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessorUserId", DbType="NVarChar(50)")]
		public string ProcessorUserId
		{
			get
			{
				return this._ProcessorUserId;
			}
			set
			{
				if ((this._ProcessorUserId != value))
				{
					this.OnProcessorUserIdChanging(value);
					this.SendPropertyChanging();
					this._ProcessorUserId = value;
					this.SendPropertyChanged("ProcessorUserId");
					this.OnProcessorUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessorPassword", DbType="NVarChar(100)")]
		public string ProcessorPassword
		{
			get
			{
				return this._ProcessorPassword;
			}
			set
			{
				if ((this._ProcessorPassword != value))
				{
					this.OnProcessorPasswordChanging(value);
					this.SendPropertyChanging();
					this._ProcessorPassword = value;
					this.SendPropertyChanged("ProcessorPassword");
					this.OnProcessorPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteLogHistory", DbType="Int")]
		public System.Nullable<int> SiteLogHistory
		{
			get
			{
				return this._SiteLogHistory;
			}
			set
			{
				if ((this._SiteLogHistory != value))
				{
					this.OnSiteLogHistoryChanging(value);
					this.SendPropertyChanging();
					this._SiteLogHistory = value;
					this.SendPropertyChanged("SiteLogHistory");
					this.OnSiteLogHistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultLanguage", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DefaultLanguage
		{
			get
			{
				return this._DefaultLanguage;
			}
			set
			{
				if ((this._DefaultLanguage != value))
				{
					this.OnDefaultLanguageChanging(value);
					this.SendPropertyChanging();
					this._DefaultLanguage = value;
					this.SendPropertyChanged("DefaultLanguage");
					this.OnDefaultLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimezoneOffset", DbType="Int NOT NULL")]
		public int TimezoneOffset
		{
			get
			{
				return this._TimezoneOffset;
			}
			set
			{
				if ((this._TimezoneOffset != value))
				{
					this.OnTimezoneOffsetChanging(value);
					this.SendPropertyChanging();
					this._TimezoneOffset = value;
					this.SendPropertyChanged("TimezoneOffset");
					this.OnTimezoneOffsetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeDirectory", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string HomeDirectory
		{
			get
			{
				return this._HomeDirectory;
			}
			set
			{
				if ((this._HomeDirectory != value))
				{
					this.OnHomeDirectoryChanging(value);
					this.SendPropertyChanging();
					this._HomeDirectory = value;
					this.SendPropertyChanged("HomeDirectory");
					this.OnHomeDirectoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageQuota", DbType="Int NOT NULL")]
		public int PageQuota
		{
			get
			{
				return this._PageQuota;
			}
			set
			{
				if ((this._PageQuota != value))
				{
					this.OnPageQuotaChanging(value);
					this.SendPropertyChanging();
					this._PageQuota = value;
					this.SendPropertyChanged("PageQuota");
					this.OnPageQuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserQuota", DbType="Int NOT NULL")]
		public int UserQuota
		{
			get
			{
				return this._UserQuota;
			}
			set
			{
				if ((this._UserQuota != value))
				{
					this.OnUserQuotaChanging(value);
					this.SendPropertyChanging();
					this._UserQuota = value;
					this.SendPropertyChanged("UserQuota");
					this.OnUserQuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalGroupID", DbType="Int")]
		public System.Nullable<int> PortalGroupID
		{
			get
			{
				return this._PortalGroupID;
			}
			set
			{
				if ((this._PortalGroupID != value))
				{
					this.OnPortalGroupIDChanging(value);
					this.SendPropertyChanging();
					this._PortalGroupID = value;
					this.SendPropertyChanged("PortalGroupID");
					this.OnPortalGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Portal_Tab", Storage="_Tabs", ThisKey="PortalID", OtherKey="PortalID")]
		public EntitySet<Tab> Tabs
		{
			get
			{
				return this._Tabs;
			}
			set
			{
				this._Tabs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Portal_Community_Visitor", Storage="_Community_Visitors", ThisKey="PortalID", OtherKey="portal_id")]
		public EntitySet<Community_Visitor> Community_Visitors
		{
			get
			{
				return this._Community_Visitors;
			}
			set
			{
				this._Community_Visitors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabs(Tab entity)
		{
			this.SendPropertyChanging();
			entity.Portal = this;
		}
		
		private void detach_Tabs(Tab entity)
		{
			this.SendPropertyChanging();
			entity.Portal = null;
		}
		
		private void attach_Community_Visitors(Community_Visitor entity)
		{
			this.SendPropertyChanging();
			entity.Portal = this;
		}
		
		private void detach_Community_Visitors(Community_Visitor entity)
		{
			this.SendPropertyChanging();
			entity.Portal = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabs")]
	public partial class Tab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TabID;
		
		private int _TabOrder;
		
		private System.Nullable<int> _PortalID;
		
		private string _TabName;
		
		private bool _IsVisible;
		
		private System.Nullable<int> _ParentId;
		
		private string _IconFile;
		
		private bool _DisableLink;
		
		private string _Title;
		
		private string _Description;
		
		private string _KeyWords;
		
		private bool _IsDeleted;
		
		private string _Url;
		
		private string _SkinSrc;
		
		private string _ContainerSrc;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<int> _RefreshInterval;
		
		private string _PageHeadText;
		
		private bool _IsSecure;
		
		private bool _PermanentRedirect;
		
		private double _SiteMapPriority;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private string _IconFileLarge;
		
		private string _CultureCode;
		
		private System.Nullable<int> _ContentItemID;
		
		private System.Guid _UniqueId;
		
		private System.Guid _VersionGuid;
		
		private System.Nullable<System.Guid> _DefaultLanguageGuid;
		
		private System.Guid _LocalizedVersionGuid;
		
		private int _Level;
		
		private string _TabPath;
		
		private bool _HasBeenPublished;
		
		private bool _IsSystem;
		
		private EntitySet<Tab> _Tabs;
		
		private EntitySet<Community_Visit> _Community_Visits;
		
		private EntityRef<Portal> _Portal;
		
		private EntityRef<Tab> _Tab1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTabIDChanging(int value);
    partial void OnTabIDChanged();
    partial void OnTabOrderChanging(int value);
    partial void OnTabOrderChanged();
    partial void OnPortalIDChanging(System.Nullable<int> value);
    partial void OnPortalIDChanged();
    partial void OnTabNameChanging(string value);
    partial void OnTabNameChanged();
    partial void OnIsVisibleChanging(bool value);
    partial void OnIsVisibleChanged();
    partial void OnParentIdChanging(System.Nullable<int> value);
    partial void OnParentIdChanged();
    partial void OnIconFileChanging(string value);
    partial void OnIconFileChanged();
    partial void OnDisableLinkChanging(bool value);
    partial void OnDisableLinkChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnKeyWordsChanging(string value);
    partial void OnKeyWordsChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnSkinSrcChanging(string value);
    partial void OnSkinSrcChanged();
    partial void OnContainerSrcChanging(string value);
    partial void OnContainerSrcChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnRefreshIntervalChanging(System.Nullable<int> value);
    partial void OnRefreshIntervalChanged();
    partial void OnPageHeadTextChanging(string value);
    partial void OnPageHeadTextChanged();
    partial void OnIsSecureChanging(bool value);
    partial void OnIsSecureChanged();
    partial void OnPermanentRedirectChanging(bool value);
    partial void OnPermanentRedirectChanged();
    partial void OnSiteMapPriorityChanging(double value);
    partial void OnSiteMapPriorityChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    partial void OnIconFileLargeChanging(string value);
    partial void OnIconFileLargeChanged();
    partial void OnCultureCodeChanging(string value);
    partial void OnCultureCodeChanged();
    partial void OnContentItemIDChanging(System.Nullable<int> value);
    partial void OnContentItemIDChanged();
    partial void OnUniqueIdChanging(System.Guid value);
    partial void OnUniqueIdChanged();
    partial void OnVersionGuidChanging(System.Guid value);
    partial void OnVersionGuidChanged();
    partial void OnDefaultLanguageGuidChanging(System.Nullable<System.Guid> value);
    partial void OnDefaultLanguageGuidChanged();
    partial void OnLocalizedVersionGuidChanging(System.Guid value);
    partial void OnLocalizedVersionGuidChanged();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    partial void OnTabPathChanging(string value);
    partial void OnTabPathChanged();
    partial void OnHasBeenPublishedChanging(bool value);
    partial void OnHasBeenPublishedChanged();
    partial void OnIsSystemChanging(bool value);
    partial void OnIsSystemChanged();
    #endregion
		
		public Tab()
		{
			this._Tabs = new EntitySet<Tab>(new Action<Tab>(this.attach_Tabs), new Action<Tab>(this.detach_Tabs));
			this._Community_Visits = new EntitySet<Community_Visit>(new Action<Community_Visit>(this.attach_Community_Visits), new Action<Community_Visit>(this.detach_Community_Visits));
			this._Portal = default(EntityRef<Portal>);
			this._Tab1 = default(EntityRef<Tab>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TabID
		{
			get
			{
				return this._TabID;
			}
			set
			{
				if ((this._TabID != value))
				{
					this.OnTabIDChanging(value);
					this.SendPropertyChanging();
					this._TabID = value;
					this.SendPropertyChanged("TabID");
					this.OnTabIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabOrder", DbType="Int NOT NULL")]
		public int TabOrder
		{
			get
			{
				return this._TabOrder;
			}
			set
			{
				if ((this._TabOrder != value))
				{
					this.OnTabOrderChanging(value);
					this.SendPropertyChanging();
					this._TabOrder = value;
					this.SendPropertyChanged("TabOrder");
					this.OnTabOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					if (this._Portal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TabName
		{
			get
			{
				return this._TabName;
			}
			set
			{
				if ((this._TabName != value))
				{
					this.OnTabNameChanging(value);
					this.SendPropertyChanging();
					this._TabName = value;
					this.SendPropertyChanged("TabName");
					this.OnTabNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit NOT NULL")]
		public bool IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this.OnIsVisibleChanging(value);
					this.SendPropertyChanging();
					this._IsVisible = value;
					this.SendPropertyChanged("IsVisible");
					this.OnIsVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int")]
		public System.Nullable<int> ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					if (this._Tab1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconFile", DbType="NVarChar(255)")]
		public string IconFile
		{
			get
			{
				return this._IconFile;
			}
			set
			{
				if ((this._IconFile != value))
				{
					this.OnIconFileChanging(value);
					this.SendPropertyChanging();
					this._IconFile = value;
					this.SendPropertyChanged("IconFile");
					this.OnIconFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisableLink", DbType="Bit NOT NULL")]
		public bool DisableLink
		{
			get
			{
				return this._DisableLink;
			}
			set
			{
				if ((this._DisableLink != value))
				{
					this.OnDisableLinkChanging(value);
					this.SendPropertyChanging();
					this._DisableLink = value;
					this.SendPropertyChanged("DisableLink");
					this.OnDisableLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWords", DbType="NVarChar(500)")]
		public string KeyWords
		{
			get
			{
				return this._KeyWords;
			}
			set
			{
				if ((this._KeyWords != value))
				{
					this.OnKeyWordsChanging(value);
					this.SendPropertyChanging();
					this._KeyWords = value;
					this.SendPropertyChanged("KeyWords");
					this.OnKeyWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(255)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkinSrc", DbType="NVarChar(200)")]
		public string SkinSrc
		{
			get
			{
				return this._SkinSrc;
			}
			set
			{
				if ((this._SkinSrc != value))
				{
					this.OnSkinSrcChanging(value);
					this.SendPropertyChanging();
					this._SkinSrc = value;
					this.SendPropertyChanged("SkinSrc");
					this.OnSkinSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContainerSrc", DbType="NVarChar(200)")]
		public string ContainerSrc
		{
			get
			{
				return this._ContainerSrc;
			}
			set
			{
				if ((this._ContainerSrc != value))
				{
					this.OnContainerSrcChanging(value);
					this.SendPropertyChanging();
					this._ContainerSrc = value;
					this.SendPropertyChanged("ContainerSrc");
					this.OnContainerSrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefreshInterval", DbType="Int")]
		public System.Nullable<int> RefreshInterval
		{
			get
			{
				return this._RefreshInterval;
			}
			set
			{
				if ((this._RefreshInterval != value))
				{
					this.OnRefreshIntervalChanging(value);
					this.SendPropertyChanging();
					this._RefreshInterval = value;
					this.SendPropertyChanged("RefreshInterval");
					this.OnRefreshIntervalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageHeadText", DbType="NVarChar(MAX)")]
		public string PageHeadText
		{
			get
			{
				return this._PageHeadText;
			}
			set
			{
				if ((this._PageHeadText != value))
				{
					this.OnPageHeadTextChanging(value);
					this.SendPropertyChanging();
					this._PageHeadText = value;
					this.SendPropertyChanged("PageHeadText");
					this.OnPageHeadTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSecure", DbType="Bit NOT NULL")]
		public bool IsSecure
		{
			get
			{
				return this._IsSecure;
			}
			set
			{
				if ((this._IsSecure != value))
				{
					this.OnIsSecureChanging(value);
					this.SendPropertyChanging();
					this._IsSecure = value;
					this.SendPropertyChanged("IsSecure");
					this.OnIsSecureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentRedirect", DbType="Bit NOT NULL")]
		public bool PermanentRedirect
		{
			get
			{
				return this._PermanentRedirect;
			}
			set
			{
				if ((this._PermanentRedirect != value))
				{
					this.OnPermanentRedirectChanging(value);
					this.SendPropertyChanging();
					this._PermanentRedirect = value;
					this.SendPropertyChanged("PermanentRedirect");
					this.OnPermanentRedirectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteMapPriority", DbType="Float NOT NULL")]
		public double SiteMapPriority
		{
			get
			{
				return this._SiteMapPriority;
			}
			set
			{
				if ((this._SiteMapPriority != value))
				{
					this.OnSiteMapPriorityChanging(value);
					this.SendPropertyChanging();
					this._SiteMapPriority = value;
					this.SendPropertyChanged("SiteMapPriority");
					this.OnSiteMapPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconFileLarge", DbType="NVarChar(255)")]
		public string IconFileLarge
		{
			get
			{
				return this._IconFileLarge;
			}
			set
			{
				if ((this._IconFileLarge != value))
				{
					this.OnIconFileLargeChanging(value);
					this.SendPropertyChanging();
					this._IconFileLarge = value;
					this.SendPropertyChanged("IconFileLarge");
					this.OnIconFileLargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CultureCode", DbType="NVarChar(10)")]
		public string CultureCode
		{
			get
			{
				return this._CultureCode;
			}
			set
			{
				if ((this._CultureCode != value))
				{
					this.OnCultureCodeChanging(value);
					this.SendPropertyChanging();
					this._CultureCode = value;
					this.SendPropertyChanged("CultureCode");
					this.OnCultureCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentItemID", DbType="Int")]
		public System.Nullable<int> ContentItemID
		{
			get
			{
				return this._ContentItemID;
			}
			set
			{
				if ((this._ContentItemID != value))
				{
					this.OnContentItemIDChanging(value);
					this.SendPropertyChanging();
					this._ContentItemID = value;
					this.SendPropertyChanged("ContentItemID");
					this.OnContentItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UniqueId
		{
			get
			{
				return this._UniqueId;
			}
			set
			{
				if ((this._UniqueId != value))
				{
					this.OnUniqueIdChanging(value);
					this.SendPropertyChanging();
					this._UniqueId = value;
					this.SendPropertyChanged("UniqueId");
					this.OnUniqueIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid VersionGuid
		{
			get
			{
				return this._VersionGuid;
			}
			set
			{
				if ((this._VersionGuid != value))
				{
					this.OnVersionGuidChanging(value);
					this.SendPropertyChanging();
					this._VersionGuid = value;
					this.SendPropertyChanged("VersionGuid");
					this.OnVersionGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultLanguageGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> DefaultLanguageGuid
		{
			get
			{
				return this._DefaultLanguageGuid;
			}
			set
			{
				if ((this._DefaultLanguageGuid != value))
				{
					this.OnDefaultLanguageGuidChanging(value);
					this.SendPropertyChanging();
					this._DefaultLanguageGuid = value;
					this.SendPropertyChanged("DefaultLanguageGuid");
					this.OnDefaultLanguageGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalizedVersionGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid LocalizedVersionGuid
		{
			get
			{
				return this._LocalizedVersionGuid;
			}
			set
			{
				if ((this._LocalizedVersionGuid != value))
				{
					this.OnLocalizedVersionGuidChanging(value);
					this.SendPropertyChanging();
					this._LocalizedVersionGuid = value;
					this.SendPropertyChanged("LocalizedVersionGuid");
					this.OnLocalizedVersionGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TabPath", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TabPath
		{
			get
			{
				return this._TabPath;
			}
			set
			{
				if ((this._TabPath != value))
				{
					this.OnTabPathChanging(value);
					this.SendPropertyChanging();
					this._TabPath = value;
					this.SendPropertyChanged("TabPath");
					this.OnTabPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasBeenPublished", DbType="Bit NOT NULL")]
		public bool HasBeenPublished
		{
			get
			{
				return this._HasBeenPublished;
			}
			set
			{
				if ((this._HasBeenPublished != value))
				{
					this.OnHasBeenPublishedChanging(value);
					this.SendPropertyChanging();
					this._HasBeenPublished = value;
					this.SendPropertyChanged("HasBeenPublished");
					this.OnHasBeenPublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSystem", DbType="Bit NOT NULL")]
		public bool IsSystem
		{
			get
			{
				return this._IsSystem;
			}
			set
			{
				if ((this._IsSystem != value))
				{
					this.OnIsSystemChanging(value);
					this.SendPropertyChanging();
					this._IsSystem = value;
					this.SendPropertyChanged("IsSystem");
					this.OnIsSystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Tab", Storage="_Tabs", ThisKey="TabID", OtherKey="ParentId")]
		public EntitySet<Tab> Tabs
		{
			get
			{
				return this._Tabs;
			}
			set
			{
				this._Tabs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Community_Visit", Storage="_Community_Visits", ThisKey="TabID", OtherKey="tab_id")]
		public EntitySet<Community_Visit> Community_Visits
		{
			get
			{
				return this._Community_Visits;
			}
			set
			{
				this._Community_Visits.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Portal_Tab", Storage="_Portal", ThisKey="PortalID", OtherKey="PortalID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Portal Portal
		{
			get
			{
				return this._Portal.Entity;
			}
			set
			{
				Portal previousValue = this._Portal.Entity;
				if (((previousValue != value) 
							|| (this._Portal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Portal.Entity = null;
						previousValue.Tabs.Remove(this);
					}
					this._Portal.Entity = value;
					if ((value != null))
					{
						value.Tabs.Add(this);
						this._PortalID = value.PortalID;
					}
					else
					{
						this._PortalID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Portal");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Tab", Storage="_Tab1", ThisKey="ParentId", OtherKey="TabID", IsForeignKey=true)]
		public Tab Tab1
		{
			get
			{
				return this._Tab1.Entity;
			}
			set
			{
				Tab previousValue = this._Tab1.Entity;
				if (((previousValue != value) 
							|| (this._Tab1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tab1.Entity = null;
						previousValue.Tabs.Remove(this);
					}
					this._Tab1.Entity = value;
					if ((value != null))
					{
						value.Tabs.Add(this);
						this._ParentId = value.TabID;
					}
					else
					{
						this._ParentId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tab1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabs(Tab entity)
		{
			this.SendPropertyChanging();
			entity.Tab1 = this;
		}
		
		private void detach_Tabs(Tab entity)
		{
			this.SendPropertyChanging();
			entity.Tab1 = null;
		}
		
		private void attach_Community_Visits(Community_Visit entity)
		{
			this.SendPropertyChanging();
			entity.Tab = this;
		}
		
		private void detach_Community_Visits(Community_Visit entity)
		{
			this.SendPropertyChanging();
			entity.Tab = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Username;
		
		private string _FirstName;
		
		private string _LastName;
		
		private bool _IsSuperUser;
		
		private System.Nullable<int> _AffiliateId;
		
		private string _Email;
		
		private string _DisplayName;
		
		private bool _UpdatePassword;
		
		private string _LastIPAddress;
		
		private bool _IsDeleted;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private System.Nullable<System.Guid> _PasswordResetToken;
		
		private System.Nullable<System.DateTime> _PasswordResetExpiration;
		
		private EntitySet<Community_Visitor> _Community_Visitors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnIsSuperUserChanging(bool value);
    partial void OnIsSuperUserChanged();
    partial void OnAffiliateIdChanging(System.Nullable<int> value);
    partial void OnAffiliateIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnUpdatePasswordChanging(bool value);
    partial void OnUpdatePasswordChanged();
    partial void OnLastIPAddressChanging(string value);
    partial void OnLastIPAddressChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    partial void OnPasswordResetTokenChanging(System.Nullable<System.Guid> value);
    partial void OnPasswordResetTokenChanged();
    partial void OnPasswordResetExpirationChanging(System.Nullable<System.DateTime> value);
    partial void OnPasswordResetExpirationChanged();
    #endregion
		
		public User()
		{
			this._Community_Visitors = new EntitySet<Community_Visitor>(new Action<Community_Visitor>(this.attach_Community_Visitors), new Action<Community_Visitor>(this.detach_Community_Visitors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSuperUser", DbType="Bit NOT NULL")]
		public bool IsSuperUser
		{
			get
			{
				return this._IsSuperUser;
			}
			set
			{
				if ((this._IsSuperUser != value))
				{
					this.OnIsSuperUserChanging(value);
					this.SendPropertyChanging();
					this._IsSuperUser = value;
					this.SendPropertyChanged("IsSuperUser");
					this.OnIsSuperUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AffiliateId", DbType="Int")]
		public System.Nullable<int> AffiliateId
		{
			get
			{
				return this._AffiliateId;
			}
			set
			{
				if ((this._AffiliateId != value))
				{
					this.OnAffiliateIdChanging(value);
					this.SendPropertyChanging();
					this._AffiliateId = value;
					this.SendPropertyChanged("AffiliateId");
					this.OnAffiliateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatePassword", DbType="Bit NOT NULL")]
		public bool UpdatePassword
		{
			get
			{
				return this._UpdatePassword;
			}
			set
			{
				if ((this._UpdatePassword != value))
				{
					this.OnUpdatePasswordChanging(value);
					this.SendPropertyChanging();
					this._UpdatePassword = value;
					this.SendPropertyChanged("UpdatePassword");
					this.OnUpdatePasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastIPAddress", DbType="NVarChar(50)")]
		public string LastIPAddress
		{
			get
			{
				return this._LastIPAddress;
			}
			set
			{
				if ((this._LastIPAddress != value))
				{
					this.OnLastIPAddressChanging(value);
					this.SendPropertyChanging();
					this._LastIPAddress = value;
					this.SendPropertyChanged("LastIPAddress");
					this.OnLastIPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordResetToken", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> PasswordResetToken
		{
			get
			{
				return this._PasswordResetToken;
			}
			set
			{
				if ((this._PasswordResetToken != value))
				{
					this.OnPasswordResetTokenChanging(value);
					this.SendPropertyChanging();
					this._PasswordResetToken = value;
					this.SendPropertyChanged("PasswordResetToken");
					this.OnPasswordResetTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordResetExpiration", DbType="DateTime")]
		public System.Nullable<System.DateTime> PasswordResetExpiration
		{
			get
			{
				return this._PasswordResetExpiration;
			}
			set
			{
				if ((this._PasswordResetExpiration != value))
				{
					this.OnPasswordResetExpirationChanging(value);
					this.SendPropertyChanging();
					this._PasswordResetExpiration = value;
					this.SendPropertyChanged("PasswordResetExpiration");
					this.OnPasswordResetExpirationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Community_Visitor", Storage="_Community_Visitors", ThisKey="UserID", OtherKey="user_id")]
		public EntitySet<Community_Visitor> Community_Visitors
		{
			get
			{
				return this._Community_Visitors;
			}
			set
			{
				this._Community_Visitors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Community_Visitors(Community_Visitor entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Community_Visitors(Community_Visitor entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Community_Visits")]
	public partial class Community_Visit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.DateTime _date;
		
		private int _visitor_id;
		
		private int _tab_id;
		
		private string _ip;
		
		private string _country;
		
		private string _region;
		
		private string _city;
		
		private string _latitude;
		
		private string _longitude;
		
		private string _language;
		
		private string _domain;
		
		private string _url;
		
		private string _user_agent;
		
		private string _device_type;
		
		private string _device;
		
		private string _platform;
		
		private string _browser;
		
		private string _referrer_domain;
		
		private string _referrer_url;
		
		private string _server;
		
		private string _campaign;
		
		private System.Nullable<System.Guid> _session_id;
		
		private System.Nullable<System.Guid> _request_id;
		
		private System.Nullable<System.Guid> _last_request_id;
		
		private EntityRef<Tab> _Tab;
		
		private EntityRef<Community_Visitor> _Community_Visitor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void Onvisitor_idChanging(int value);
    partial void Onvisitor_idChanged();
    partial void Ontab_idChanging(int value);
    partial void Ontab_idChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnlatitudeChanging(string value);
    partial void OnlatitudeChanged();
    partial void OnlongitudeChanging(string value);
    partial void OnlongitudeChanged();
    partial void OnlanguageChanging(string value);
    partial void OnlanguageChanged();
    partial void OndomainChanging(string value);
    partial void OndomainChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void Onuser_agentChanging(string value);
    partial void Onuser_agentChanged();
    partial void Ondevice_typeChanging(string value);
    partial void Ondevice_typeChanged();
    partial void OndeviceChanging(string value);
    partial void OndeviceChanged();
    partial void OnplatformChanging(string value);
    partial void OnplatformChanged();
    partial void OnbrowserChanging(string value);
    partial void OnbrowserChanged();
    partial void Onreferrer_domainChanging(string value);
    partial void Onreferrer_domainChanged();
    partial void Onreferrer_urlChanging(string value);
    partial void Onreferrer_urlChanged();
    partial void OnserverChanging(string value);
    partial void OnserverChanged();
    partial void OncampaignChanging(string value);
    partial void OncampaignChanged();
    partial void Onsession_idChanging(System.Nullable<System.Guid> value);
    partial void Onsession_idChanged();
    partial void Onrequest_idChanging(System.Nullable<System.Guid> value);
    partial void Onrequest_idChanged();
    partial void Onlast_request_idChanging(System.Nullable<System.Guid> value);
    partial void Onlast_request_idChanged();
    #endregion
		
		public Community_Visit()
		{
			this._Tab = default(EntityRef<Tab>);
			this._Community_Visitor = default(EntityRef<Community_Visitor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visitor_id", DbType="Int NOT NULL")]
		public int visitor_id
		{
			get
			{
				return this._visitor_id;
			}
			set
			{
				if ((this._visitor_id != value))
				{
					if (this._Community_Visitor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onvisitor_idChanging(value);
					this.SendPropertyChanging();
					this._visitor_id = value;
					this.SendPropertyChanged("visitor_id");
					this.Onvisitor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tab_id", DbType="Int NOT NULL")]
		public int tab_id
		{
			get
			{
				return this._tab_id;
			}
			set
			{
				if ((this._tab_id != value))
				{
					if (this._Tab.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontab_idChanging(value);
					this.SendPropertyChanging();
					this._tab_id = value;
					this.SendPropertyChanged("tab_id");
					this.Ontab_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_language", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string language
		{
			get
			{
				return this._language;
			}
			set
			{
				if ((this._language != value))
				{
					this.OnlanguageChanging(value);
					this.SendPropertyChanging();
					this._language = value;
					this.SendPropertyChanged("language");
					this.OnlanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domain", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string domain
		{
			get
			{
				return this._domain;
			}
			set
			{
				if ((this._domain != value))
				{
					this.OndomainChanging(value);
					this.SendPropertyChanging();
					this._domain = value;
					this.SendPropertyChanged("domain");
					this.OndomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(2048) NOT NULL", CanBeNull=false)]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_agent", DbType="NVarChar(512) NOT NULL", CanBeNull=false)]
		public string user_agent
		{
			get
			{
				return this._user_agent;
			}
			set
			{
				if ((this._user_agent != value))
				{
					this.Onuser_agentChanging(value);
					this.SendPropertyChanging();
					this._user_agent = value;
					this.SendPropertyChanged("user_agent");
					this.Onuser_agentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string device_type
		{
			get
			{
				return this._device_type;
			}
			set
			{
				if ((this._device_type != value))
				{
					this.Ondevice_typeChanging(value);
					this.SendPropertyChanging();
					this._device_type = value;
					this.SendPropertyChanged("device_type");
					this.Ondevice_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string device
		{
			get
			{
				return this._device;
			}
			set
			{
				if ((this._device != value))
				{
					this.OndeviceChanging(value);
					this.SendPropertyChanging();
					this._device = value;
					this.SendPropertyChanged("device");
					this.OndeviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string platform
		{
			get
			{
				return this._platform;
			}
			set
			{
				if ((this._platform != value))
				{
					this.OnplatformChanging(value);
					this.SendPropertyChanging();
					this._platform = value;
					this.SendPropertyChanged("platform");
					this.OnplatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_browser", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string browser
		{
			get
			{
				return this._browser;
			}
			set
			{
				if ((this._browser != value))
				{
					this.OnbrowserChanging(value);
					this.SendPropertyChanging();
					this._browser = value;
					this.SendPropertyChanged("browser");
					this.OnbrowserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referrer_domain", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string referrer_domain
		{
			get
			{
				return this._referrer_domain;
			}
			set
			{
				if ((this._referrer_domain != value))
				{
					this.Onreferrer_domainChanging(value);
					this.SendPropertyChanging();
					this._referrer_domain = value;
					this.SendPropertyChanged("referrer_domain");
					this.Onreferrer_domainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referrer_url", DbType="NVarChar(2048) NOT NULL", CanBeNull=false)]
		public string referrer_url
		{
			get
			{
				return this._referrer_url;
			}
			set
			{
				if ((this._referrer_url != value))
				{
					this.Onreferrer_urlChanging(value);
					this.SendPropertyChanging();
					this._referrer_url = value;
					this.SendPropertyChanged("referrer_url");
					this.Onreferrer_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_server", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string server
		{
			get
			{
				return this._server;
			}
			set
			{
				if ((this._server != value))
				{
					this.OnserverChanging(value);
					this.SendPropertyChanging();
					this._server = value;
					this.SendPropertyChanged("server");
					this.OnserverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string campaign
		{
			get
			{
				return this._campaign;
			}
			set
			{
				if ((this._campaign != value))
				{
					this.OncampaignChanging(value);
					this.SendPropertyChanging();
					this._campaign = value;
					this.SendPropertyChanged("campaign");
					this.OncampaignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> session_id
		{
			get
			{
				return this._session_id;
			}
			set
			{
				if ((this._session_id != value))
				{
					this.Onsession_idChanging(value);
					this.SendPropertyChanging();
					this._session_id = value;
					this.SendPropertyChanged("session_id");
					this.Onsession_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_request_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> request_id
		{
			get
			{
				return this._request_id;
			}
			set
			{
				if ((this._request_id != value))
				{
					this.Onrequest_idChanging(value);
					this.SendPropertyChanging();
					this._request_id = value;
					this.SendPropertyChanged("request_id");
					this.Onrequest_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_request_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> last_request_id
		{
			get
			{
				return this._last_request_id;
			}
			set
			{
				if ((this._last_request_id != value))
				{
					this.Onlast_request_idChanging(value);
					this.SendPropertyChanging();
					this._last_request_id = value;
					this.SendPropertyChanged("last_request_id");
					this.Onlast_request_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Community_Visit", Storage="_Tab", ThisKey="tab_id", OtherKey="TabID", IsForeignKey=true)]
		public Tab Tab
		{
			get
			{
				return this._Tab.Entity;
			}
			set
			{
				Tab previousValue = this._Tab.Entity;
				if (((previousValue != value) 
							|| (this._Tab.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tab.Entity = null;
						previousValue.Community_Visits.Remove(this);
					}
					this._Tab.Entity = value;
					if ((value != null))
					{
						value.Community_Visits.Add(this);
						this._tab_id = value.TabID;
					}
					else
					{
						this._tab_id = default(int);
					}
					this.SendPropertyChanged("Tab");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Community_Visitor_Community_Visit", Storage="_Community_Visitor", ThisKey="visitor_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Community_Visitor Community_Visitor
		{
			get
			{
				return this._Community_Visitor.Entity;
			}
			set
			{
				Community_Visitor previousValue = this._Community_Visitor.Entity;
				if (((previousValue != value) 
							|| (this._Community_Visitor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Community_Visitor.Entity = null;
						previousValue.Community_Visits.Remove(this);
					}
					this._Community_Visitor.Entity = value;
					if ((value != null))
					{
						value.Community_Visits.Add(this);
						this._visitor_id = value.id;
					}
					else
					{
						this._visitor_id = default(int);
					}
					this.SendPropertyChanged("Community_Visitor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Community_Visitors")]
	public partial class Community_Visitor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _portal_id;
		
		private System.Nullable<int> _user_id;
		
		private System.DateTime _created_on_date;
		
		private EntitySet<Community_Visit> _Community_Visits;
		
		private EntityRef<Portal> _Portal;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onportal_idChanging(int value);
    partial void Onportal_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Oncreated_on_dateChanging(System.DateTime value);
    partial void Oncreated_on_dateChanged();
    #endregion
		
		public Community_Visitor()
		{
			this._Community_Visits = new EntitySet<Community_Visit>(new Action<Community_Visit>(this.attach_Community_Visits), new Action<Community_Visit>(this.detach_Community_Visits));
			this._Portal = default(EntityRef<Portal>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portal_id", DbType="Int NOT NULL")]
		public int portal_id
		{
			get
			{
				return this._portal_id;
			}
			set
			{
				if ((this._portal_id != value))
				{
					if (this._Portal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onportal_idChanging(value);
					this.SendPropertyChanging();
					this._portal_id = value;
					this.SendPropertyChanged("portal_id");
					this.Onportal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_on_date", DbType="DateTime NOT NULL")]
		public System.DateTime created_on_date
		{
			get
			{
				return this._created_on_date;
			}
			set
			{
				if ((this._created_on_date != value))
				{
					this.Oncreated_on_dateChanging(value);
					this.SendPropertyChanging();
					this._created_on_date = value;
					this.SendPropertyChanged("created_on_date");
					this.Oncreated_on_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Community_Visitor_Community_Visit", Storage="_Community_Visits", ThisKey="id", OtherKey="visitor_id")]
		public EntitySet<Community_Visit> Community_Visits
		{
			get
			{
				return this._Community_Visits;
			}
			set
			{
				this._Community_Visits.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Portal_Community_Visitor", Storage="_Portal", ThisKey="portal_id", OtherKey="PortalID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Portal Portal
		{
			get
			{
				return this._Portal.Entity;
			}
			set
			{
				Portal previousValue = this._Portal.Entity;
				if (((previousValue != value) 
							|| (this._Portal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Portal.Entity = null;
						previousValue.Community_Visitors.Remove(this);
					}
					this._Portal.Entity = value;
					if ((value != null))
					{
						value.Community_Visitors.Add(this);
						this._portal_id = value.PortalID;
					}
					else
					{
						this._portal_id = default(int);
					}
					this.SendPropertyChanged("Portal");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Community_Visitor", Storage="_User", ThisKey="user_id", OtherKey="UserID", IsForeignKey=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Community_Visitors.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Community_Visitors.Add(this);
						this._user_id = value.UserID;
					}
					else
					{
						this._user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Community_Visits(Community_Visit entity)
		{
			this.SendPropertyChanging();
			entity.Community_Visitor = this;
		}
		
		private void detach_Community_Visits(Community_Visit entity)
		{
			this.SendPropertyChanging();
			entity.Community_Visitor = null;
		}
	}
}
#pragma warning restore 1591
