<?xml version="1.0" encoding="utf-8"?><Database Name="dnn9" EntityNamespace="Dnn.WebAnalytics" ContextNamespace="Dnn.WebAnalytics" Class="DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=dnn9;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SiteSqlServer" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Portals" Member="Portals">
    <Type Name="Portal">
      <Column Name="PortalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserRegistration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BannerAdvertising" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdministratorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="HostFee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="HostSpace" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdministratorRoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegisteredRoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PaymentProcessor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProcessorUserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProcessorPassword" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SiteLogHistory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DefaultLanguage" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimezoneOffset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HomeDirectory" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PageQuota" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserQuota" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortalGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Portal_Tab" Member="Tabs" ThisKey="PortalID" OtherKey="PortalID" Type="Tab" />
      <Association Name="Portal_Community_Visitor" Member="Community_Visitors" ThisKey="PortalID" OtherKey="portal_id" Type="Community_Visitor" />
    </Type>
  </Table>
  <Table Name="dbo.Tabs" Member="Tabs">
    <Type Name="Tab">
      <Column Name="TabID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TabOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TabName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IconFile" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DisableLink" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="KeyWords" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SkinSrc" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ContainerSrc" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RefreshInterval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PageHeadText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsSecure" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PermanentRedirect" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SiteMapPriority" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IconFileLarge" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CultureCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ContentItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UniqueId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VersionGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DefaultLanguageGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LocalizedVersionGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TabPath" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="HasBeenPublished" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSystem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Tab_Tab" Member="Tabs" ThisKey="TabID" OtherKey="ParentId" Type="Tab" />
      <Association Name="Tab_Community_Visit" Member="Community_Visits" ThisKey="TabID" OtherKey="tab_id" Type="Community_Visit" />
      <Association Name="Portal_Tab" Member="Portal" ThisKey="PortalID" OtherKey="PortalID" Type="Portal" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Tab_Tab" Member="Tab1" ThisKey="ParentId" OtherKey="TabID" Type="Tab" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsSuperUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AffiliateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UpdatePassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastIPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordResetToken" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PasswordResetExpiration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Community_Visitor" Member="Community_Visitors" ThisKey="UserID" OtherKey="user_id" Type="Community_Visitor" />
    </Type>
  </Table>
  <Table Name="dbo.Community_Visits" Member="Community_Visits">
    <Type Name="Community_Visit">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="visitor_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tab_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ip" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="region" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="language" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="domain" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="NVarChar(2048) NOT NULL" CanBeNull="false" />
      <Column Name="user_agent" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="device_type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="device" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="platform" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="browser" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="referrer_domain" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="referrer_url" Type="System.String" DbType="NVarChar(2048) NOT NULL" CanBeNull="false" />
      <Column Name="server" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="campaign" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="session_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="request_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="last_request_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Tab_Community_Visit" Member="Tab" ThisKey="tab_id" OtherKey="TabID" Type="Tab" IsForeignKey="true" />
      <Association Name="Community_Visitor_Community_Visit" Member="Community_Visitor" ThisKey="visitor_id" OtherKey="id" Type="Community_Visitor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Community_Visitors" Member="Community_Visitors">
    <Type Name="Community_Visitor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="portal_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_on_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Community_Visitor_Community_Visit" Member="Community_Visits" ThisKey="id" OtherKey="visitor_id" Type="Community_Visit" />
      <Association Name="Portal_Community_Visitor" Member="Portal" ThisKey="portal_id" OtherKey="PortalID" Type="Portal" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_Community_Visitor" Member="User" ThisKey="user_id" OtherKey="UserID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>